### ISSUE TITLE
Error on using example message send

### ISSUE THREAD

**Issue by tomchambers2** [nulltask/osc-cli#1]
```
~/Downloads/oscpack > osc /foo bar baz
/Users/tomchambers/.nvm/versions/node/v4.2.1/lib/node_modules/osc-cli/node_modules/osc-min/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213
          throw new Error("Use CoffeeScript.register() or require the coffee-script/register module to require " + ext + " files.");
          ^

Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/Users/tomchambers/.nvm/versions/node/v4.2.1/lib/node_modules/osc-cli/node_modules/osc-min/node_modules/coffee-script/lib/coffee-script/coffee-script.js:213:17)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/tomchambers/.nvm/versions/node/v4.2.1/lib/node_modules/osc-cli/node_modules/osc-min/lib/index.js:95:11)
  at Object.<anonymous> (/Users/tomchambers/.nvm/versions/node/v4.2.1/lib/node_modules/osc-cli/node_modules/osc-min/lib/index.js:165:4)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/tomchambers/.nvm/versions/node/v4.2.1/lib/node_modules/osc-cli/bin/osc:12:11)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

~/Downloads/oscpack > 
```

**Comment by nulltask** [comment]
great!
